In [17]:
import numpy as np
import pandas as pd
from scipy.spatial import distance
from sklearn.preprocessing import LabelEncoder

from sklearn.cluster import KMeans
from K_means import *

## Load Ecoil Dataset

In [18]:
# a list of the name of columns
names = ["Sequence_Name", "mcg", "gvh", "lip", "chg", "aac", "alm1", 
         "alm2", "class"]
# load the data from CSV file
df = pd.read_csv('ecoli.csv', header=None, names= names)
df.head()

Sequence_Name   mcg   gvh   lip  chg   aac  alm1  alm2 class
0     AAT_ECOLI  0.49  0.29  0.48  0.5  0.56  0.24  0.35    cp
1    ACEA_ECOLI  0.07  0.40  0.48  0.5  0.54  0.35  0.44    cp
2    ACEK_ECOLI  0.56  0.40  0.48  0.5  0.49  0.37  0.46    cp
3    ACKA_ECOLI  0.59  0.49  0.48  0.5  0.52  0.45  0.36    cp
4     ADI_ECOLI  0.23  0.32  0.48  0.5  0.55  0.25  0.35    cp

Drop the Sequence_Name and label the class using int

In [25]:
# transform the dataset
le = LabelEncoder()
df['class'] = le.fit_transform(df['class'])

# Drop the Sequence name
df = df.drop(["Sequence_Name"], axis = 1)
df.head()

mcg   gvh   lip  chg   aac  alm1  alm2  class
0  0.49  0.29  0.48  0.5  0.56  0.24  0.35      0
1  0.07  0.40  0.48  0.5  0.54  0.35  0.44      0
2  0.56  0.40  0.48  0.5  0.49  0.37  0.46      0
3  0.59  0.49  0.48  0.5  0.52  0.45  0.36      0
4  0.23  0.32  0.48  0.5  0.55  0.25  0.35      0

In [38]:
X = df.iloc[:, 0:-1].values
y = df.iloc[:, -1]

## Implementation of k-means

In [39]:
# using the custom k-means to calculate the centroids

cluster_centers = kmeans(X, 2)

print('The centroids:\n', cluster_centers)

[[ 0.33  0.45  0.48  0.5   0.45  0.88  0.89]
 [ 0.43  0.4   0.48  0.5   0.39  0.28  0.39]]
[[ 0.57605769  0.48586538  0.495       0.5         0.56278846  0.76807692
   0.77596154]
 [ 0.46599138  0.50633621  0.49568966  0.50215517  0.47189655  0.38008621
   0.37590517]]
[[ 0.5871028   0.48700935  0.49943925  0.5         0.5611215   0.76102804
   0.77130841]
 [ 0.45938865  0.50606987  0.49362445  0.50218341  0.47148472  0.37829694
   0.37283843]]
The centroids:
 [[ 0.5871028   0.48700935  0.49943925  0.5         0.5611215   0.76102804
   0.77130841]
 [ 0.45938865  0.50606987  0.49362445  0.50218341  0.47148472  0.37829694
   0.37283843]]


In [40]:
# using Scikit-learn to get the centroids
skl_kmeans = KMeans(n_clusters=2, random_state=0).fit(X)

In [41]:
skl_kmeans.cluster_centers_

array([[ 0.5871028 ,  0.48700935,  0.49943925,  0.5       ,  0.5611215 ,
         0.76102804,  0.77130841],
       [ 0.45938865,  0.50606987,  0.49362445,  0.50218341,  0.47148472,
         0.37829694,  0.37283843]])