In [1]:
import numpy as np
import pandas as pd
from scipy.spatial import distance
from sklearn.preprocessing import LabelEncoder

from sklearn.cluster import KMeans
from K_means import *

## Load Ecoil Dataset

In [2]:
df = pd.read_csv('ecoli.csv', header= None)

In [3]:
df.head()

0     1     2     3    4     5     6     7   8
0   AAT_ECOLI  0.49  0.29  0.48  0.5  0.56  0.24  0.35  cp
1  ACEA_ECOLI  0.07  0.40  0.48  0.5  0.54  0.35  0.44  cp
2  ACEK_ECOLI  0.56  0.40  0.48  0.5  0.49  0.37  0.46  cp
3  ACKA_ECOLI  0.59  0.49  0.48  0.5  0.52  0.45  0.36  cp
4   ADI_ECOLI  0.23  0.32  0.48  0.5  0.55  0.25  0.35  cp

In [4]:
# transform the dataset
le = LabelEncoder()
df[8] = le.fit_transform(df[8])
df.head()

0     1     2     3    4     5     6     7  8
0   AAT_ECOLI  0.49  0.29  0.48  0.5  0.56  0.24  0.35  0
1  ACEA_ECOLI  0.07  0.40  0.48  0.5  0.54  0.35  0.44  0
2  ACEK_ECOLI  0.56  0.40  0.48  0.5  0.49  0.37  0.46  0
3  ACKA_ECOLI  0.59  0.49  0.48  0.5  0.52  0.45  0.36  0
4   ADI_ECOLI  0.23  0.32  0.48  0.5  0.55  0.25  0.35  0

In [5]:
data = df.iloc[:, 1:-1]
data.head()

1     2     3    4     5     6     7
0  0.49  0.29  0.48  0.5  0.56  0.24  0.35
1  0.07  0.40  0.48  0.5  0.54  0.35  0.44
2  0.56  0.40  0.48  0.5  0.49  0.37  0.46
3  0.59  0.49  0.48  0.5  0.52  0.45  0.36
4  0.23  0.32  0.48  0.5  0.55  0.25  0.35

## Implementation of k-means

In [6]:
cluster_centers = kmeans(data.values, 2)
cluster_centers

[[ 0.33  0.45  0.48  0.5   0.45  0.88  0.89]
 [ 0.43  0.4   0.48  0.5   0.39  0.28  0.39]]
[[ 0.57605769  0.48586538  0.495       0.5         0.56278846  0.76807692
   0.77596154]
 [ 0.46599138  0.50633621  0.49568966  0.50215517  0.47189655  0.38008621
   0.37590517]]
[[ 0.5871028   0.48700935  0.49943925  0.5         0.5611215   0.76102804
   0.77130841]
 [ 0.45938865  0.50606987  0.49362445  0.50218341  0.47148472  0.37829694
   0.37283843]]


array([[ 0.5871028 ,  0.48700935,  0.49943925,  0.5       ,  0.5611215 ,
         0.76102804,  0.77130841],
       [ 0.45938865,  0.50606987,  0.49362445,  0.50218341,  0.47148472,
         0.37829694,  0.37283843]])

In [7]:
skl_kmeans = KMeans(n_clusters=2, random_state=0).fit(data)

In [8]:
skl_kmeans.cluster_centers_

array([[ 0.5871028 ,  0.48700935,  0.49943925,  0.5       ,  0.5611215 ,
         0.76102804,  0.77130841],
       [ 0.45938865,  0.50606987,  0.49362445,  0.50218341,  0.47148472,
         0.37829694,  0.37283843]])